spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}
  jpa:
    properties:
      hibernate:
        query:
          plan_cache_max_size: 192 # limit query plan cache max size
  datasource:
    url: jdbc:mysql://mysql.bosong.online:10039/ApolloPortalDB?characterEncoding=utf8
    username: apollo
    password: apollo
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
server:
  port: 8070
  compression:
    enabled: true
  tomcat:
    use-relative-redirects: true

logging:
  file:
    name: /opt/logs/100003173/apollo-portal.log

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP
    ldap:
      enabled: false # disable ldap health check by default
cat:
  app:
    id: apollo-portal
  server:
    port: 2280
    servers: 49.233.166.95
    http:
      port: 8080