# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ 1.8.1 ]
    paths-ignore: [ '**/*.md' ]
  pull_request:
    branches: [ 1.8.1 ]
    paths-ignore: [ '**/*.md' ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        jdk: [8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: docker push
      run: |
        mvn -ntp clean install -Dapollo_profile=github -DskipTests=true
        pwd && ls
        cd apollo-configservice && mvn -ntp clean package -Dapollo_profile=github docker:build -DskipTests=true
        cd apollo-adminservice && mvn -ntp clean package  -Dapollo_profile=github docker:build -DskipTests=true
        cd apollo-portal && mvn -ntp clean package -Dapollo_profile=github docker:build -DskipTests=true
        docker login --username=${{secrets.USERNAME}}  --password=${{secrets.PASSWORD}}  ${{secrets.REGISTRY}}
        docker images
        docker push ${{secrets.REGISTRY}}/bosong/apollo-configservice:1.8.1
        docker push ${{secrets.REGISTRY}}/bosong/apollo-configservice:latest
        docker push ${{secrets.REGISTRY}}/bosong/apollo-adminservice:1.8.1
        docker push ${{secrets.REGISTRY}}/bosong/apollo-adminservice:latest
        docker push ${{secrets.REGISTRY}}/bosong/apollo-portal:1.8.1
        docker push ${{secrets.REGISTRY}}/bosong/apollo-portal:latest
